version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family_integral_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_NAME: FamilyIntegralAPI
      APP_ENV: production
      APP_KEY: base64:3jihBRPNcepkZ46+4fb3+vHjK8VlNkVPSeuOkZQTi2U=
      APP_DEBUG: "false"
      APP_URL: http://100.53.118.174:8000
      APP_TIMEZONE: America/Cancun
      APP_LOCALE: es

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: family_integral
      DB_USERNAME: root
      DB_PASSWORD: ""

      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync

    depends_on:
      db:
        condition: service_healthy
    networks:
      - family_network

  db:
    image: mysql:8.0
    container_name: family_integral_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: family_integral
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - family_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: family_integral_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db
    networks:
      - family_network

volumes:
  mysql_data:

networks:
  family_network:
    driver: bridge