name: CI - Family Integral

on:
  push:
    branches: [main, develop, Pruebas/Glovales]
  pull_request:
    branches: [main, develop, Pruebas/Glovales]

jobs:

  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite

      - name: Instalar dependencias
        run: composer install --no-progress --prefer-dist

      - name: Copiar .env
        run: cp .env.example .env

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Crear base de datos SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Ejecutar tests
        run: php artisan test


  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install || true

      - name: Build
        run: npm run build --if-present

      - name: Tests frontend
        run: npm test --if-present
